export const authCopy = {
  "zh-CN": {
    language: "English",
    eyebrow: "团队与 AI 的共同工作空间",
    title: "让每一次讨论，都向成果更近一步。",
    description: "把团队成员、AI 角色、项目对话与共享文档放在同一处，清楚协作，也清楚负责。",
    benefits: [
      "团队和 AI 在同一上下文中协作",
      "重要修改可追踪、可审核、可撤销",
      "权限随工作区与角色明确配置",
    ],
    signIn: "登录",
    signUp: "创建账户",
    welcome: "欢迎回来",
    welcomeDetail: "选择身份入口；协作成员和空间管理再选择工作区",
    selectIdentity: "选择身份入口",
    selectRole: "选择角色",
    portalMember: "协作成员",
    portalWorkspace: "空间管理",
    portalSystem: "系统管理",
    portalMemberDesc: "进入房间、处理待办、推进文档",
    portalWorkspaceDesc: "管理成员、AI 角色和安全边界",
    portalSystemDesc: "租户生命周期、平台健康与全局策略",
    roleMemberOption: "协作成员",
    roleGuestOption: "访客",
    roleAdminOption: "空间管理员",
    roleOwnerOption: "所有者",
    name: "你的姓名",
    namePlaceholder: "例如：李明",
    email: "工作邮箱",
    emailPlaceholder: "name@company.com",
    password: "密码",
    passwordPlaceholder: "至少 10 个字符",
    submitAs: "以{role}身份登录",
    selectWorkspace: "选择工作区",
    workspace: "工作区",
    workspacePending: "选择你的团队或项目",
    workspacePendingHint: "工作区跟账号绑定，登录后才能列出你加入的团队。",
    emptyWorkspaceList: "这个账户还没有工作区",
    enterWorkspace: "进入{workspace}",
    createFirstWorkspace: "创建工作区",
    working: "正在验证…",
    showPassword: "显示密码",
    hidePassword: "隐藏密码",
    emailInvalid: "请输入有效的工作邮箱。",
    passwordRequired: "请输入至少 10 个字符的密码。",
    invalid: "邮箱或密码不正确，请检查后重试。",
    duplicate: "这个邮箱已经注册，请直接登录。",
    generic: "暂时无法完成请求，请稍后重试。",
    sessionUnreadable: "登录已通过，但工作区暂时无法读取，请刷新后重试。",
  },
  "en-US": {
    language: "中文",
    eyebrow: "A shared workspace for teams and AI",
    title: "Move every conversation closer to an outcome.",
    description:
      "Bring people, AI roles, project conversations, and shared documents into one accountable workspace.",
    benefits: [
      "Teams and AI share one working context",
      "Important changes stay reviewable and reversible",
      "Permissions are explicit by workspace and role",
    ],
    signIn: "Sign in",
    signUp: "Create account",
    welcome: "Welcome back",
    welcomeDetail:
      "Choose an identity portal; collaborators and workspace admins also pick a workspace",
    selectIdentity: "Choose an identity portal",
    selectRole: "Choose a role",
    portalMember: "Collaborator",
    portalWorkspace: "Workspace admin",
    portalSystem: "System admin",
    portalMemberDesc: "Enter rooms, handle inbox items, and move documents forward",
    portalWorkspaceDesc: "Manage members, AI roles, and safety boundaries",
    portalSystemDesc: "Tenant lifecycle, platform health, and global policy",
    roleMemberOption: "Collaborator",
    roleGuestOption: "Guest",
    roleAdminOption: "Workspace admin",
    roleOwnerOption: "Owner",
    name: "Your name",
    namePlaceholder: "e.g. Alex Chen",
    email: "Work email",
    emailPlaceholder: "name@company.com",
    password: "Password",
    passwordPlaceholder: "At least 10 characters",
    submitAs: "Sign in as {role}",
    selectWorkspace: "Choose workspace",
    workspace: "Workspace",
    workspacePending: "Choose your team or project",
    workspacePendingHint: "Workspaces belong to your account, so they appear after you sign in.",
    emptyWorkspaceList: "This account has no workspace yet",
    enterWorkspace: "Enter {workspace}",
    createFirstWorkspace: "Create a workspace",
    working: "Checking…",
    showPassword: "Show password",
    hidePassword: "Hide password",
    emailInvalid: "Enter a valid work email.",
    passwordRequired: "Enter a password with at least 10 characters.",
    invalid: "The email or password is incorrect. Please try again.",
    duplicate: "This email is already registered. Sign in instead.",
    generic: "We could not complete the request. Please try again.",
    sessionUnreadable:
      "You are signed in, but workspaces could not be loaded. Refresh and try again.",
  },
} as const;

export type AuthLocale = keyof typeof authCopy;
