export const authCopy = {
  "zh-CN": {
    language: "English",
    eyebrow: "团队与 AI 的共同工作空间",
    title: "让每一次讨论，都向成果更近一步。",
    description: "把团队成员、AI 角色、项目对话与共享文档放在同一处，清楚协作，也清楚负责。",
    benefits: [
      "团队和 AI 在同一上下文中协作",
      "重要修改可追踪、可审核、可撤销",
      "权限随工作区与角色明确配置",
    ],
    signIn: "登录",
    signUp: "创建账户",
    welcome: "欢迎回来",
    welcomeDetail: "选择身份入口并进入工作台",
    createTitle: "创建你的 HaloAI 账户",
    createDetail: "选择身份入口后建立第一个工作区。",
    selectIdentity: "选择身份入口",
    portalMember: "协作成员",
    portalWorkspace: "空间管理",
    portalSystem: "系统管理",
    portalMemberDesc: "进入房间、处理待办、推进文档",
    portalWorkspaceDesc: "管理成员、AI 角色和安全边界",
    portalSystemDesc: "租户生命周期、平台健康与全局策略",
    name: "你的姓名",
    namePlaceholder: "例如：李明",
    email: "工作邮箱",
    emailPlaceholder: "name@company.com",
    password: "密码",
    passwordPlaceholder: "至少 10 个字符",
    submitSignIn: "进入工作区",
    submitAs: "以{role}身份登录",
    submitSignUp: "创建并继续",
    working: "正在验证…",
    showPassword: "显示密码",
    hidePassword: "隐藏密码",
    security: "会话凭据保存在受保护 Cookie 中，不会暴露给页面脚本。",
    invalid: "邮箱或密码不正确，请检查后重试。",
    duplicate: "这个邮箱已经注册，请直接登录。",
    generic: "暂时无法完成请求，请稍后重试。",
  },
  "en-US": {
    language: "中文",
    eyebrow: "A shared workspace for teams and AI",
    title: "Move every conversation closer to an outcome.",
    description:
      "Bring people, AI roles, project conversations, and shared documents into one accountable workspace.",
    benefits: [
      "Teams and AI share one working context",
      "Important changes stay reviewable and reversible",
      "Permissions are explicit by workspace and role",
    ],
    signIn: "Sign in",
    signUp: "Create account",
    welcome: "Welcome back",
    welcomeDetail: "Choose an identity portal and enter the workspace",
    createTitle: "Create your HaloAI account",
    createDetail: "Choose an identity portal, then create your first workspace.",
    selectIdentity: "Choose an identity portal",
    portalMember: "Collaborator",
    portalWorkspace: "Workspace admin",
    portalSystem: "System admin",
    portalMemberDesc: "Enter rooms, handle inbox items, and move documents forward",
    portalWorkspaceDesc: "Manage members, AI roles, and safety boundaries",
    portalSystemDesc: "Tenant lifecycle, platform health, and global policy",
    name: "Your name",
    namePlaceholder: "e.g. Alex Chen",
    email: "Work email",
    emailPlaceholder: "name@company.com",
    password: "Password",
    passwordPlaceholder: "At least 10 characters",
    submitSignIn: "Enter workspace",
    submitAs: "Sign in as {role}",
    submitSignUp: "Create and continue",
    working: "Checking…",
    showPassword: "Show password",
    hidePassword: "Hide password",
    security: "Session credentials stay in a protected cookie and are not exposed to page scripts.",
    invalid: "The email or password is incorrect. Please try again.",
    duplicate: "This email is already registered. Sign in instead.",
    generic: "We could not complete the request. Please try again.",
  },
} as const;

export type AuthLocale = keyof typeof authCopy;
