-- 为尚未注释的表与字段补齐中文 COMMENT。不改变列类型、约束或数据。
-- 已进入共享环境的 0003 不得改写，本文件只向前追加。

COMMENT ON TABLE "actor_role_assignments" IS '把访问角色分配给 Actor，并限定作用域';
COMMENT ON TABLE "agent_actors" IS 'AI 主体与人设的一对一绑定，不能拥有人类登录会话';
COMMENT ON TABLE "agent_version_capability_grants" IS '某个 Agent 版本被封存的能力授权快照';
COMMENT ON TABLE "agent_version_tool_grants" IS '某个 Agent 版本被封存的工具授权快照';
COMMENT ON TABLE "agent_versions" IS 'AI 人设的不可变版本快照，发布后禁止改写';
COMMENT ON TABLE "context_manifest_items" IS '进入模型上下文的单条授权条目，不含完整正文';
COMMENT ON TABLE "context_manifests" IS '一次运行进入模型上下文的授权清单摘要';
COMMENT ON TABLE "document_versions" IS '文档的不可变命名检查点，恢复必须新建版本';
COMMENT ON TABLE "mentions" IS '消息中的结构化提及关系，禁止事后从文本猜测';
COMMENT ON TABLE "message_revisions" IS '消息修订历史，仅追加，不覆盖原始消息';
COMMENT ON TABLE "message_tombstones" IS '消息删除事实，不复制被隐藏正文';
COMMENT ON TABLE "project_memberships" IS '项目成员资格与项目内角色';
COMMENT ON TABLE "proposal_operations" IS '文档提案中的单条可审阅操作';
COMMENT ON TABLE "resource_grants" IS '针对具体资源的能力授予或拒绝';
COMMENT ON TABLE "role_capability_grants" IS '角色被授予或拒绝的能力事实';
COMMENT ON TABLE "room_memberships" IS '房间成员资格、静音与已读进度';
COMMENT ON TABLE "run_events" IS 'Agent 运行事件流，区分耐久与瞬时事件';
COMMENT ON TABLE "run_messages" IS '运行与房间消息的关联';
COMMENT ON TABLE "run_steps" IS 'Agent 运行中的可恢复步骤';
COMMENT ON TABLE "tool_calls" IS '工具调用摘要与执行边界，不含明文参数或密钥';
COMMENT ON TABLE "tool_capabilities" IS '工作空间可用工具能力及其风险与策略';
COMMENT ON TABLE "tool_effects" IS '工具调用的外部副作用确认状态';
COMMENT ON TABLE "usage_ledger_entries" IS '用量与费用账本，支持预留、结算与调整';
COMMENT ON TABLE "yjs_snapshots" IS '协作文档的 Yjs 二进制检查点';

COMMENT ON COLUMN "access_roles"."id" IS '主键';
COMMENT ON COLUMN "access_roles"."workspace_id" IS '所属工作空间';
COMMENT ON COLUMN "access_roles"."description" IS '说明';
COMMENT ON COLUMN "access_roles"."status" IS '状态';
COMMENT ON COLUMN "access_roles"."built_in" IS '内置角色标记';
COMMENT ON COLUMN "access_roles"."created_at" IS '创建时间';
COMMENT ON COLUMN "access_roles"."updated_at" IS '最后更新时间';
COMMENT ON COLUMN "actor_role_assignments"."id" IS '主键';
COMMENT ON COLUMN "actor_role_assignments"."workspace_id" IS '所属工作空间';
COMMENT ON COLUMN "actor_role_assignments"."actor_id" IS '关联 Actor';
COMMENT ON COLUMN "actor_role_assignments"."role_id" IS '访问角色';
COMMENT ON COLUMN "actor_role_assignments"."scope" IS '授权作用域';
COMMENT ON COLUMN "actor_role_assignments"."scope_id" IS '作用域资源标识';
COMMENT ON COLUMN "actor_role_assignments"."status" IS '状态';
COMMENT ON COLUMN "actor_role_assignments"."granted_by_actor_id" IS '授权人 Actor';
COMMENT ON COLUMN "actor_role_assignments"."valid_from" IS '生效时间';
COMMENT ON COLUMN "actor_role_assignments"."expires_at" IS '过期时间';
COMMENT ON COLUMN "actor_role_assignments"."revoked_at" IS '撤销时间';
COMMENT ON COLUMN "actor_role_assignments"."created_at" IS '创建时间';
COMMENT ON COLUMN "actor_role_assignments"."updated_at" IS '最后更新时间';
COMMENT ON COLUMN "actors"."archived_at" IS '归档时间';
COMMENT ON COLUMN "actors"."created_at" IS '创建时间';
COMMENT ON COLUMN "actors"."updated_at" IS '最后更新时间';
COMMENT ON COLUMN "agent_actors"."actor_id" IS '关联 Actor';
COMMENT ON COLUMN "agent_actors"."workspace_id" IS '所属工作空间';
COMMENT ON COLUMN "agent_actors"."agent_profile_id" IS '所属 AI 人设';
COMMENT ON COLUMN "agent_actors"."created_at" IS '创建时间';
COMMENT ON COLUMN "agent_profiles"."handle" IS '工作空间内唯一句柄';
COMMENT ON COLUMN "agent_profiles"."summary" IS '摘要';
COMMENT ON COLUMN "agent_profiles"."visual_identity" IS '视觉标识';
COMMENT ON COLUMN "agent_profiles"."owner_actor_id" IS '负责人 Actor';
COMMENT ON COLUMN "agent_profiles"."archived_at" IS '归档时间';
COMMENT ON COLUMN "agent_profiles"."created_at" IS '创建时间';
COMMENT ON COLUMN "agent_profiles"."updated_at" IS '最后更新时间';
COMMENT ON COLUMN "agent_runs"."id" IS '主键';
COMMENT ON COLUMN "agent_runs"."project_id" IS '所属项目';
COMMENT ON COLUMN "agent_runs"."room_id" IS '所属房间';
COMMENT ON COLUMN "agent_runs"."agent_actor_id" IS '执行该操作的 AI Actor';
COMMENT ON COLUMN "agent_runs"."agent_version_id" IS '使用的 Agent 版本';
COMMENT ON COLUMN "agent_runs"."parent_run_id" IS '父运行，用于重试链路';
COMMENT ON COLUMN "agent_runs"."trigger_message_id" IS '触发本运行的消息';
COMMENT ON COLUMN "agent_runs"."idempotency_key" IS '幂等键';
COMMENT ON COLUMN "agent_runs"."purpose" IS '运行目的';
COMMENT ON COLUMN "agent_runs"."state_version" IS '状态版本，用于乐观锁';
COMMENT ON COLUMN "agent_runs"."attempt" IS '尝试次数';
COMMENT ON COLUMN "agent_runs"."authorization_snapshot_ref" IS '启动时授权快照引用';
COMMENT ON COLUMN "agent_runs"."authorization_snapshot_digest" IS '授权快照摘要';
COMMENT ON COLUMN "agent_runs"."policy_version" IS '策略版本';
COMMENT ON COLUMN "agent_runs"."budget_policy_version" IS '预算策略版本';
COMMENT ON COLUMN "agent_runs"."budget_policy" IS '预算策略快照';
COMMENT ON COLUMN "agent_runs"."budget_reservation_key" IS '预算预留键';
COMMENT ON COLUMN "agent_runs"."consumed_input_tokens" IS '已消耗输入 token';
COMMENT ON COLUMN "agent_runs"."consumed_output_tokens" IS '已消耗输出 token';
COMMENT ON COLUMN "agent_runs"."consumed_cost_minor" IS '已消耗费用最小货币单位';
COMMENT ON COLUMN "agent_runs"."completed_turns" IS '已完成轮次数';
COMMENT ON COLUMN "agent_runs"."completed_tool_calls" IS '已完成工具调用数';
COMMENT ON COLUMN "agent_runs"."participant_count" IS '参与者数量';
COMMENT ON COLUMN "agent_runs"."deadline_at" IS '截止时间';
COMMENT ON COLUMN "agent_runs"."lease_owner" IS '租约持有者';
COMMENT ON COLUMN "agent_runs"."lease_expires_at" IS '租约到期时间';
COMMENT ON COLUMN "agent_runs"."heartbeat_at" IS '最近心跳时间';
COMMENT ON COLUMN "agent_runs"."cancel_requested_at" IS '取消请求时间';
COMMENT ON COLUMN "agent_runs"."started_at" IS '开始时间';
COMMENT ON COLUMN "agent_runs"."ended_at" IS '结束时间';
COMMENT ON COLUMN "agent_runs"."result_summary" IS '结果摘要';
COMMENT ON COLUMN "agent_runs"."terminal_reason_code" IS '终态原因码';
COMMENT ON COLUMN "agent_runs"."created_at" IS '创建时间';
COMMENT ON COLUMN "agent_runs"."updated_at" IS '最后更新时间';
COMMENT ON COLUMN "agent_version_capability_grants"."id" IS '主键';
COMMENT ON COLUMN "agent_version_capability_grants"."workspace_id" IS '所属工作空间';
COMMENT ON COLUMN "agent_version_capability_grants"."agent_version_id" IS '使用的 Agent 版本';
COMMENT ON COLUMN "agent_version_capability_grants"."capability_key" IS '能力稳定键';
COMMENT ON COLUMN "agent_version_capability_grants"."effect" IS '授权效果：allow / deny';
COMMENT ON COLUMN "agent_version_capability_grants"."constraints" IS '结构化限制条件';
COMMENT ON COLUMN "agent_version_capability_grants"."created_by_actor_id" IS '创建人 Actor';
COMMENT ON COLUMN "agent_version_capability_grants"."created_at" IS '创建时间';
COMMENT ON COLUMN "agent_version_tool_grants"."id" IS '主键';
COMMENT ON COLUMN "agent_version_tool_grants"."workspace_id" IS '所属工作空间';
COMMENT ON COLUMN "agent_version_tool_grants"."agent_version_id" IS '使用的 Agent 版本';
COMMENT ON COLUMN "agent_version_tool_grants"."tool_capability_id" IS '工具能力';
COMMENT ON COLUMN "agent_version_tool_grants"."constraints" IS '结构化限制条件';
COMMENT ON COLUMN "agent_version_tool_grants"."max_calls_per_run" IS '单次运行最大调用次数';
COMMENT ON COLUMN "agent_version_tool_grants"."created_by_actor_id" IS '创建人 Actor';
COMMENT ON COLUMN "agent_version_tool_grants"."created_at" IS '创建时间';
COMMENT ON COLUMN "agent_versions"."id" IS '主键';
COMMENT ON COLUMN "agent_versions"."workspace_id" IS '所属工作空间';
COMMENT ON COLUMN "agent_versions"."agent_profile_id" IS '所属 AI 人设';
COMMENT ON COLUMN "agent_versions"."version_number" IS '版本号';
COMMENT ON COLUMN "agent_versions"."status" IS '状态';
COMMENT ON COLUMN "agent_versions"."responsibility" IS '职责说明';
COMMENT ON COLUMN "agent_versions"."non_responsibilities" IS '明确不负责的事项';
COMMENT ON COLUMN "agent_versions"."instruction_document_ref" IS '受治理指令文档引用';
COMMENT ON COLUMN "agent_versions"."instruction_digest" IS '指令文档摘要';
COMMENT ON COLUMN "agent_versions"."model_policy" IS '模型策略';
COMMENT ON COLUMN "agent_versions"."fallback_policy" IS '回退策略';
COMMENT ON COLUMN "agent_versions"."output_contract" IS '输出契约';
COMMENT ON COLUMN "agent_versions"."knowledge_selectors" IS '知识选择器';
COMMENT ON COLUMN "agent_versions"."collaboration_policy" IS '协作策略';
COMMENT ON COLUMN "agent_versions"."budget_policy" IS '预算策略快照';
COMMENT ON COLUMN "agent_versions"."policy_version" IS '策略版本';
COMMENT ON COLUMN "agent_versions"."schema_version" IS 'schema 版本';
COMMENT ON COLUMN "agent_versions"."content_digest" IS '内容摘要';
COMMENT ON COLUMN "agent_versions"."created_by_actor_id" IS '创建人 Actor';
COMMENT ON COLUMN "agent_versions"."published_by_actor_id" IS '发布人 Actor';
COMMENT ON COLUMN "agent_versions"."published_at" IS '发布时间';
COMMENT ON COLUMN "agent_versions"."retired_at" IS '退役时间';
COMMENT ON COLUMN "agent_versions"."created_at" IS '创建时间';
COMMENT ON COLUMN "approvals"."project_id" IS '所属项目';
COMMENT ON COLUMN "approvals"."delegated_by_actor_id" IS '委托人 Actor';
COMMENT ON COLUMN "approvals"."reviewed_by_actor_id" IS '审阅人 Actor';
COMMENT ON COLUMN "approvals"."agent_version_id" IS '使用的 Agent 版本';
COMMENT ON COLUMN "approvals"."run_id" IS '关联 Agent 运行';
COMMENT ON COLUMN "approvals"."tool_capability_id" IS '工具能力';
COMMENT ON COLUMN "approvals"."tool_call_id" IS '关联工具调用';
COMMENT ON COLUMN "approvals"."document_proposal_id" IS '关联文档提案';
COMMENT ON COLUMN "approvals"."capability_key" IS '能力稳定键';
COMMENT ON COLUMN "approvals"."operation_type" IS '操作类型';
COMMENT ON COLUMN "approvals"."argument_digest" IS '参数摘要，不含明文';
COMMENT ON COLUMN "approvals"."operation_summary" IS '操作摘要';
COMMENT ON COLUMN "approvals"."affected_resources" IS '受影响资源摘要';
COMMENT ON COLUMN "approvals"."risk" IS '风险等级';
COMMENT ON COLUMN "approvals"."risk_explanation" IS '风险说明';
COMMENT ON COLUMN "approvals"."policy_version" IS '策略版本';
COMMENT ON COLUMN "approvals"."idempotency_key" IS '幂等键';
COMMENT ON COLUMN "approvals"."expires_at" IS '过期时间';
COMMENT ON COLUMN "approvals"."decision_comment" IS '决定说明';
COMMENT ON COLUMN "approvals"."decided_at" IS '作出决定的时间';
COMMENT ON COLUMN "approvals"."consumed_at" IS '消费时间';
COMMENT ON COLUMN "approvals"."cancelled_at" IS '取消时间';
COMMENT ON COLUMN "approvals"."created_at" IS '创建时间';
COMMENT ON COLUMN "approvals"."updated_at" IS '最后更新时间';
COMMENT ON COLUMN "audit_events"."on_behalf_of_actor_id" IS '被代理的 Actor';
COMMENT ON COLUMN "audit_events"."workspace_membership_id" IS '工作空间成员资格';
COMMENT ON COLUMN "audit_events"."approval_id" IS '关联审批';
COMMENT ON COLUMN "audit_events"."run_id" IS '关联 Agent 运行';
COMMENT ON COLUMN "audit_events"."agent_version_id" IS '使用的 Agent 版本';
COMMENT ON COLUMN "audit_events"."tool_call_id" IS '关联工具调用';
COMMENT ON COLUMN "audit_events"."session_id" IS '登录会话';
COMMENT ON COLUMN "audit_events"."trace_id" IS '追踪标识';
COMMENT ON COLUMN "audit_events"."resource_type" IS '资源类型';
COMMENT ON COLUMN "audit_events"."resource_id" IS '资源标识';
COMMENT ON COLUMN "audit_events"."decision" IS '策略决定';
COMMENT ON COLUMN "audit_events"."policy_version" IS '策略版本';
COMMENT ON COLUMN "audit_events"."obligations" IS '附加义务';
COMMENT ON COLUMN "audit_events"."request_summary_hash" IS '请求摘要哈希';
COMMENT ON COLUMN "audit_events"."before_hash" IS '变更前摘要';
COMMENT ON COLUMN "audit_events"."after_hash" IS '变更后摘要';
COMMENT ON COLUMN "audit_events"."reason_code" IS '原因码';
COMMENT ON COLUMN "audit_events"."error_code" IS '错误码';
COMMENT ON COLUMN "audit_events"."source_ip" IS '来源 IP';
COMMENT ON COLUMN "audit_events"."user_agent" IS '客户端标识';
COMMENT ON COLUMN "audit_events"."sanitized_metadata" IS '已脱敏元数据';
COMMENT ON COLUMN "audit_events"."occurred_at" IS '发生时间';
COMMENT ON COLUMN "auth_accounts"."account_id" IS '提供者侧账户标识';
COMMENT ON COLUMN "auth_accounts"."access_token" IS '访问令牌，仅认证角色可访问';
COMMENT ON COLUMN "auth_accounts"."refresh_token" IS '刷新令牌，仅认证角色可访问';
COMMENT ON COLUMN "auth_accounts"."id_token" IS '身份令牌，仅认证角色可访问';
COMMENT ON COLUMN "auth_accounts"."access_token_expires_at" IS '访问令牌过期时间';
COMMENT ON COLUMN "auth_accounts"."refresh_token_expires_at" IS '刷新令牌过期时间';
COMMENT ON COLUMN "auth_accounts"."scope" IS '授权作用域';
COMMENT ON COLUMN "auth_accounts"."created_at" IS '创建时间';
COMMENT ON COLUMN "auth_accounts"."updated_at" IS '最后更新时间';
COMMENT ON COLUMN "auth_sessions"."ip_address" IS '来源 IP';
COMMENT ON COLUMN "auth_sessions"."user_agent" IS '客户端标识';
COMMENT ON COLUMN "auth_sessions"."created_at" IS '创建时间';
COMMENT ON COLUMN "auth_sessions"."updated_at" IS '最后更新时间';
COMMENT ON COLUMN "auth_verifications"."id" IS '主键';
COMMENT ON COLUMN "auth_verifications"."created_at" IS '创建时间';
COMMENT ON COLUMN "auth_verifications"."updated_at" IS '最后更新时间';
COMMENT ON COLUMN "capabilities"."description_key" IS '说明文案键';
COMMENT ON COLUMN "capabilities"."risk" IS '风险等级';
COMMENT ON COLUMN "capabilities"."created_at" IS '创建时间';
COMMENT ON COLUMN "context_manifest_items"."id" IS '主键';
COMMENT ON COLUMN "context_manifest_items"."workspace_id" IS '所属工作空间';
COMMENT ON COLUMN "context_manifest_items"."manifest_id" IS '所属上下文清单';
COMMENT ON COLUMN "context_manifest_items"."ordinal" IS '顺序号';
COMMENT ON COLUMN "context_manifest_items"."kind" IS '类型';
COMMENT ON COLUMN "context_manifest_items"."resource_type" IS '资源类型';
COMMENT ON COLUMN "context_manifest_items"."resource_id" IS '资源标识';
COMMENT ON COLUMN "context_manifest_items"."resource_version" IS '资源版本';
COMMENT ON COLUMN "context_manifest_items"."content_digest" IS '内容摘要';
COMMENT ON COLUMN "context_manifest_items"."token_estimate" IS '预估 token 数';
COMMENT ON COLUMN "context_manifest_items"."trust_class" IS '信任级别';
COMMENT ON COLUMN "context_manifest_items"."decision" IS '策略决定';
COMMENT ON COLUMN "context_manifest_items"."decision_reason_code" IS '决定原因码';
COMMENT ON COLUMN "context_manifest_items"."included" IS '是否实际纳入上下文';
COMMENT ON COLUMN "context_manifest_items"."created_at" IS '创建时间';
COMMENT ON COLUMN "context_manifests"."id" IS '主键';
COMMENT ON COLUMN "context_manifests"."workspace_id" IS '所属工作空间';
COMMENT ON COLUMN "context_manifests"."run_id" IS '关联 Agent 运行';
COMMENT ON COLUMN "context_manifests"."step_id" IS '关联运行步骤';
COMMENT ON COLUMN "context_manifests"."policy_version" IS '策略版本';
COMMENT ON COLUMN "context_manifests"."manifest_digest" IS '清单摘要';
COMMENT ON COLUMN "context_manifests"."total_item_count" IS '候选条目总数';
COMMENT ON COLUMN "context_manifests"."included_item_count" IS '纳入条目数';
COMMENT ON COLUMN "context_manifests"."truncated_item_count" IS '被裁剪条目数';
COMMENT ON COLUMN "context_manifests"."token_estimate" IS '预估 token 数';
COMMENT ON COLUMN "context_manifests"."created_at" IS '创建时间';
COMMENT ON COLUMN "document_proposals"."id" IS '主键';
COMMENT ON COLUMN "document_proposals"."workspace_id" IS '所属工作空间';
COMMENT ON COLUMN "document_proposals"."proposal_version" IS '提案版本号';
COMMENT ON COLUMN "document_proposals"."base_version_id" IS '提案基于的文档版本';
COMMENT ON COLUMN "document_proposals"."base_content_digest" IS '提案基线内容摘要';
COMMENT ON COLUMN "document_proposals"."base_state_vector" IS '提案基线 Yjs 状态向量';
COMMENT ON COLUMN "document_proposals"."agent_actor_id" IS '执行该操作的 AI Actor';
COMMENT ON COLUMN "document_proposals"."agent_version_id" IS '使用的 Agent 版本';
COMMENT ON COLUMN "document_proposals"."delegated_by_actor_id" IS '委托人 Actor';
COMMENT ON COLUMN "document_proposals"."run_id" IS '关联 Agent 运行';
COMMENT ON COLUMN "document_proposals"."rationale_summary" IS '理由摘要';
COMMENT ON COLUMN "document_proposals"."citations" IS '引用列表';
COMMENT ON COLUMN "document_proposals"."policy_decision" IS '策略决定';
COMMENT ON COLUMN "document_proposals"."policy_version" IS '策略版本';
COMMENT ON COLUMN "document_proposals"."idempotency_key" IS '幂等键';
COMMENT ON COLUMN "document_proposals"."expires_at" IS '过期时间';
COMMENT ON COLUMN "document_proposals"."reviewed_by_actor_id" IS '审阅人 Actor';
COMMENT ON COLUMN "document_proposals"."reviewed_at" IS '审阅时间';
COMMENT ON COLUMN "document_proposals"."applied_snapshot_id" IS '应用后生成的快照';
COMMENT ON COLUMN "document_proposals"."applied_version_id" IS '应用后生成的文档版本';
COMMENT ON COLUMN "document_proposals"."created_at" IS '创建时间';
COMMENT ON COLUMN "document_proposals"."updated_at" IS '最后更新时间';
COMMENT ON COLUMN "document_versions"."id" IS '主键';
COMMENT ON COLUMN "document_versions"."workspace_id" IS '所属工作空间';
COMMENT ON COLUMN "document_versions"."document_id" IS '所属文档';
COMMENT ON COLUMN "document_versions"."version_number" IS '版本号';
COMMENT ON COLUMN "document_versions"."name" IS '名称';
COMMENT ON COLUMN "document_versions"."cause" IS '形成该版本的原因';
COMMENT ON COLUMN "document_versions"."snapshot_id" IS '引用的 Yjs 快照';
COMMENT ON COLUMN "document_versions"."content_digest" IS '内容摘要';
COMMENT ON COLUMN "document_versions"."rich_text_projection_ref" IS '富文本投影引用';
COMMENT ON COLUMN "document_versions"."plain_text_digest" IS '纯文本投影摘要';
COMMENT ON COLUMN "document_versions"."created_by_actor_id" IS '创建人 Actor';
COMMENT ON COLUMN "document_versions"."run_id" IS '关联 Agent 运行';
COMMENT ON COLUMN "document_versions"."created_at" IS '创建时间';
COMMENT ON COLUMN "documents"."project_id" IS '所属项目';
COMMENT ON COLUMN "documents"."room_id" IS '所属房间';
COMMENT ON COLUMN "documents"."document_schema_version" IS '文档 schema 版本';
COMMENT ON COLUMN "documents"."archived_at" IS '归档时间';
COMMENT ON COLUMN "documents"."deleted_at" IS '删除时间';
COMMENT ON COLUMN "documents"."created_at" IS '创建时间';
COMMENT ON COLUMN "documents"."updated_at" IS '最后更新时间';
COMMENT ON COLUMN "human_actors"."created_at" IS '创建时间';
COMMENT ON COLUMN "mentions"."id" IS '主键';
COMMENT ON COLUMN "mentions"."workspace_id" IS '所属工作空间';
COMMENT ON COLUMN "mentions"."message_id" IS '关联消息';
COMMENT ON COLUMN "mentions"."target_actor_id" IS '被提及的 Actor';
COMMENT ON COLUMN "mentions"."semantic_node_id" IS '结构化提及节点';
COMMENT ON COLUMN "mentions"."range_start" IS '提及起始位置';
COMMENT ON COLUMN "mentions"."range_end" IS '提及结束位置';
COMMENT ON COLUMN "mentions"."created_at" IS '创建时间';
COMMENT ON COLUMN "message_revisions"."id" IS '主键';
COMMENT ON COLUMN "message_revisions"."workspace_id" IS '所属工作空间';
COMMENT ON COLUMN "message_revisions"."message_id" IS '关联消息';
COMMENT ON COLUMN "message_revisions"."revision_number" IS '修订号';
COMMENT ON COLUMN "message_revisions"."edited_by_actor_id" IS '修订人 Actor';
COMMENT ON COLUMN "message_revisions"."parts" IS '结构化内容块';
COMMENT ON COLUMN "message_revisions"."content_digest" IS '内容摘要';
COMMENT ON COLUMN "message_revisions"."reason" IS '原因说明';
COMMENT ON COLUMN "message_revisions"."created_at" IS '创建时间';
COMMENT ON COLUMN "message_tombstones"."id" IS '主键';
COMMENT ON COLUMN "message_tombstones"."workspace_id" IS '所属工作空间';
COMMENT ON COLUMN "message_tombstones"."message_id" IS '关联消息';
COMMENT ON COLUMN "message_tombstones"."tombstoned_by_actor_id" IS '执行删除的 Actor';
COMMENT ON COLUMN "message_tombstones"."reason_code" IS '原因码';
COMMENT ON COLUMN "message_tombstones"."erasure_job_reference" IS '擦除任务引用';
COMMENT ON COLUMN "message_tombstones"."created_at" IS '创建时间';
COMMENT ON COLUMN "messages"."sequence" IS '序号';
COMMENT ON COLUMN "messages"."client_mutation_id" IS '客户端幂等键';
COMMENT ON COLUMN "messages"."reply_to_message_id" IS '回复的消息';
COMMENT ON COLUMN "messages"."thread_root_id" IS '线程根消息';
COMMENT ON COLUMN "messages"."parts" IS '结构化内容块';
COMMENT ON COLUMN "messages"."content_digest" IS '内容摘要';
COMMENT ON COLUMN "messages"."created_at" IS '创建时间';
COMMENT ON COLUMN "outbox_events"."id" IS '主键';
COMMENT ON COLUMN "outbox_events"."workspace_id" IS '所属工作空间';
COMMENT ON COLUMN "outbox_events"."event_id" IS '领域事件标识';
COMMENT ON COLUMN "outbox_events"."aggregate_type" IS '聚合根类型';
COMMENT ON COLUMN "outbox_events"."aggregate_id" IS '聚合根标识';
COMMENT ON COLUMN "outbox_events"."schema_version" IS 'schema 版本';
COMMENT ON COLUMN "outbox_events"."status" IS '状态';
COMMENT ON COLUMN "outbox_events"."attempts" IS '已尝试投递次数';
COMMENT ON COLUMN "outbox_events"."idempotency_key" IS '幂等键';
COMMENT ON COLUMN "outbox_events"."available_at" IS '最早可处理时间';
COMMENT ON COLUMN "outbox_events"."lease_owner" IS '租约持有者';
COMMENT ON COLUMN "outbox_events"."lease_expires_at" IS '租约到期时间';
COMMENT ON COLUMN "outbox_events"."published_at" IS '发布时间';
COMMENT ON COLUMN "outbox_events"."last_error_code" IS '最近错误码';
COMMENT ON COLUMN "outbox_events"."created_at" IS '创建时间';
COMMENT ON COLUMN "outbox_events"."updated_at" IS '最后更新时间';
COMMENT ON COLUMN "project_memberships"."id" IS '主键';
COMMENT ON COLUMN "project_memberships"."workspace_id" IS '所属工作空间';
COMMENT ON COLUMN "project_memberships"."project_id" IS '所属项目';
COMMENT ON COLUMN "project_memberships"."actor_id" IS '关联 Actor';
COMMENT ON COLUMN "project_memberships"."status" IS '状态';
COMMENT ON COLUMN "project_memberships"."added_by_actor_id" IS '添加人 Actor';
COMMENT ON COLUMN "project_memberships"."joined_at" IS '加入时间';
COMMENT ON COLUMN "project_memberships"."left_at" IS '离开时间';
COMMENT ON COLUMN "project_memberships"."created_at" IS '创建时间';
COMMENT ON COLUMN "project_memberships"."updated_at" IS '最后更新时间';
COMMENT ON COLUMN "project_memberships"."role" IS '角色';
COMMENT ON COLUMN "projects"."description" IS '说明';
COMMENT ON COLUMN "projects"."goal" IS '目标说明';
COMMENT ON COLUMN "projects"."expected_artifact" IS '预期交付物';
COMMENT ON COLUMN "projects"."completion_criteria" IS '完成标准';
COMMENT ON COLUMN "projects"."created_by_actor_id" IS '创建人 Actor';
COMMENT ON COLUMN "projects"."archived_at" IS '归档时间';
COMMENT ON COLUMN "projects"."created_at" IS '创建时间';
COMMENT ON COLUMN "projects"."updated_at" IS '最后更新时间';
COMMENT ON COLUMN "proposal_operations"."id" IS '主键';
COMMENT ON COLUMN "proposal_operations"."workspace_id" IS '所属工作空间';
COMMENT ON COLUMN "proposal_operations"."proposal_id" IS '所属提案';
COMMENT ON COLUMN "proposal_operations"."ordinal" IS '顺序号';
COMMENT ON COLUMN "proposal_operations"."type" IS '类型';
COMMENT ON COLUMN "proposal_operations"."target_node_id" IS '目标文档节点';
COMMENT ON COLUMN "proposal_operations"."operation" IS '操作载荷';
COMMENT ON COLUMN "proposal_operations"."operation_digest" IS '操作摘要';
COMMENT ON COLUMN "proposal_operations"."rationale_summary" IS '理由摘要';
COMMENT ON COLUMN "proposal_operations"."citations" IS '引用列表';
COMMENT ON COLUMN "proposal_operations"."status" IS '状态';
COMMENT ON COLUMN "proposal_operations"."decided_by_actor_id" IS '作出决定的 Actor';
COMMENT ON COLUMN "proposal_operations"."decided_at" IS '作出决定的时间';
COMMENT ON COLUMN "proposal_operations"."applied_at" IS '应用时间';
COMMENT ON COLUMN "proposal_operations"."created_at" IS '创建时间';
COMMENT ON COLUMN "proposal_operations"."updated_at" IS '最后更新时间';
COMMENT ON COLUMN "resource_grants"."id" IS '主键';
COMMENT ON COLUMN "resource_grants"."workspace_id" IS '所属工作空间';
COMMENT ON COLUMN "resource_grants"."actor_id" IS '关联 Actor';
COMMENT ON COLUMN "resource_grants"."role_id" IS '访问角色';
COMMENT ON COLUMN "resource_grants"."resource_type" IS '资源类型';
COMMENT ON COLUMN "resource_grants"."resource_id" IS '资源标识';
COMMENT ON COLUMN "resource_grants"."capability_key" IS '能力稳定键';
COMMENT ON COLUMN "resource_grants"."effect" IS '授权效果：allow / deny';
COMMENT ON COLUMN "resource_grants"."status" IS '状态';
COMMENT ON COLUMN "resource_grants"."conditions" IS '附加条件，禁止放凭据或可执行表达式';
COMMENT ON COLUMN "resource_grants"."granted_by_actor_id" IS '授权人 Actor';
COMMENT ON COLUMN "resource_grants"."expires_at" IS '过期时间';
COMMENT ON COLUMN "resource_grants"."created_at" IS '创建时间';
COMMENT ON COLUMN "resource_grants"."updated_at" IS '最后更新时间';
COMMENT ON COLUMN "role_capability_grants"."id" IS '主键';
COMMENT ON COLUMN "role_capability_grants"."workspace_id" IS '所属工作空间';
COMMENT ON COLUMN "role_capability_grants"."role_id" IS '访问角色';
COMMENT ON COLUMN "role_capability_grants"."capability_key" IS '能力稳定键';
COMMENT ON COLUMN "role_capability_grants"."effect" IS '授权效果：allow / deny';
COMMENT ON COLUMN "role_capability_grants"."constraints" IS '结构化限制条件';
COMMENT ON COLUMN "role_capability_grants"."granted_by_actor_id" IS '授权人 Actor';
COMMENT ON COLUMN "role_capability_grants"."created_at" IS '创建时间';
COMMENT ON COLUMN "role_capability_grants"."updated_at" IS '最后更新时间';
COMMENT ON COLUMN "room_memberships"."id" IS '主键';
COMMENT ON COLUMN "room_memberships"."workspace_id" IS '所属工作空间';
COMMENT ON COLUMN "room_memberships"."room_id" IS '所属房间';
COMMENT ON COLUMN "room_memberships"."actor_id" IS '关联 Actor';
COMMENT ON COLUMN "room_memberships"."status" IS '状态';
COMMENT ON COLUMN "room_memberships"."added_by_actor_id" IS '添加人 Actor';
COMMENT ON COLUMN "room_memberships"."muted" IS '是否静音该房间';
COMMENT ON COLUMN "room_memberships"."last_read_sequence" IS '已读消息序号';
COMMENT ON COLUMN "room_memberships"."joined_at" IS '加入时间';
COMMENT ON COLUMN "room_memberships"."left_at" IS '离开时间';
COMMENT ON COLUMN "room_memberships"."created_at" IS '创建时间';
COMMENT ON COLUMN "room_memberships"."updated_at" IS '最后更新时间';
COMMENT ON COLUMN "rooms"."expected_artifact" IS '预期交付物';
COMMENT ON COLUMN "rooms"."completion_criteria" IS '完成标准';
COMMENT ON COLUMN "rooms"."visibility" IS '可见范围';
COMMENT ON COLUMN "rooms"."collaboration_mode" IS '协作模式';
COMMENT ON COLUMN "rooms"."created_by_actor_id" IS '创建人 Actor';
COMMENT ON COLUMN "rooms"."last_sequence" IS '房间已分配的最大消息序号';
COMMENT ON COLUMN "rooms"."archived_at" IS '归档时间';
COMMENT ON COLUMN "rooms"."created_at" IS '创建时间';
COMMENT ON COLUMN "rooms"."updated_at" IS '最后更新时间';
COMMENT ON COLUMN "run_events"."id" IS '主键';
COMMENT ON COLUMN "run_events"."workspace_id" IS '所属工作空间';
COMMENT ON COLUMN "run_events"."run_id" IS '关联 Agent 运行';
COMMENT ON COLUMN "run_events"."stream_id" IS '事件流标识';
COMMENT ON COLUMN "run_events"."sequence" IS '序号';
COMMENT ON COLUMN "run_events"."type" IS '类型';
COMMENT ON COLUMN "run_events"."payload_version" IS '载荷 schema 版本';
COMMENT ON COLUMN "run_events"."payload" IS '事件载荷';
COMMENT ON COLUMN "run_events"."durability" IS '事件耐久性：durable / transient';
COMMENT ON COLUMN "run_events"."actor_id" IS '关联 Actor';
COMMENT ON COLUMN "run_events"."correlation_id" IS '关联标识';
COMMENT ON COLUMN "run_events"."causation_id" IS '因果事件标识';
COMMENT ON COLUMN "run_events"."attempt" IS '尝试次数';
COMMENT ON COLUMN "run_events"."occurred_at" IS '发生时间';
COMMENT ON COLUMN "run_messages"."id" IS '主键';
COMMENT ON COLUMN "run_messages"."workspace_id" IS '所属工作空间';
COMMENT ON COLUMN "run_messages"."run_id" IS '关联 Agent 运行';
COMMENT ON COLUMN "run_messages"."message_id" IS '关联消息';
COMMENT ON COLUMN "run_messages"."role" IS '角色';
COMMENT ON COLUMN "run_messages"."created_at" IS '创建时间';
COMMENT ON COLUMN "run_steps"."id" IS '主键';
COMMENT ON COLUMN "run_steps"."workspace_id" IS '所属工作空间';
COMMENT ON COLUMN "run_steps"."run_id" IS '关联 Agent 运行';
COMMENT ON COLUMN "run_steps"."sequence" IS '序号';
COMMENT ON COLUMN "run_steps"."kind" IS '类型';
COMMENT ON COLUMN "run_steps"."status" IS '状态';
COMMENT ON COLUMN "run_steps"."attempt" IS '尝试次数';
COMMENT ON COLUMN "run_steps"."idempotency_key" IS '幂等键';
COMMENT ON COLUMN "run_steps"."input_digest" IS '输入摘要';
COMMENT ON COLUMN "run_steps"."output_digest" IS '输出摘要';
COMMENT ON COLUMN "run_steps"."observable_summary" IS '可观察摘要，不含机密';
COMMENT ON COLUMN "run_steps"."error_code" IS '错误码';
COMMENT ON COLUMN "run_steps"."started_at" IS '开始时间';
COMMENT ON COLUMN "run_steps"."ended_at" IS '结束时间';
COMMENT ON COLUMN "run_steps"."created_at" IS '创建时间';
COMMENT ON COLUMN "run_steps"."updated_at" IS '最后更新时间';
COMMENT ON COLUMN "tool_calls"."id" IS '主键';
COMMENT ON COLUMN "tool_calls"."workspace_id" IS '所属工作空间';
COMMENT ON COLUMN "tool_calls"."run_id" IS '关联 Agent 运行';
COMMENT ON COLUMN "tool_calls"."step_id" IS '关联运行步骤';
COMMENT ON COLUMN "tool_calls"."tool_capability_id" IS '工具能力';
COMMENT ON COLUMN "tool_calls"."tool_version_number" IS '工具版本号';
COMMENT ON COLUMN "tool_calls"."schema_digest" IS 'schema 摘要';
COMMENT ON COLUMN "tool_calls"."execution_principal_actor_id" IS '实际执行主体 Actor';
COMMENT ON COLUMN "tool_calls"."status" IS '状态';
COMMENT ON COLUMN "tool_calls"."risk" IS '风险等级';
COMMENT ON COLUMN "tool_calls"."argument_digest" IS '参数摘要，不含明文';
COMMENT ON COLUMN "tool_calls"."argument_summary" IS '参数可读摘要';
COMMENT ON COLUMN "tool_calls"."credential_binding_ref" IS '密钥绑定引用，不含明文';
COMMENT ON COLUMN "tool_calls"."network_policy_version" IS '网络策略版本';
COMMENT ON COLUMN "tool_calls"."idempotency_key" IS '幂等键';
COMMENT ON COLUMN "tool_calls"."external_idempotency_key" IS '外部幂等键';
COMMENT ON COLUMN "tool_calls"."result_digest" IS '结果摘要';
COMMENT ON COLUMN "tool_calls"."result_classification" IS '结果分类';
COMMENT ON COLUMN "tool_calls"."duration_ms" IS '耗时毫秒';
COMMENT ON COLUMN "tool_calls"."usage_summary" IS '用量摘要';
COMMENT ON COLUMN "tool_calls"."error_code" IS '错误码';
COMMENT ON COLUMN "tool_calls"."requested_at" IS '请求时间';
COMMENT ON COLUMN "tool_calls"."started_at" IS '开始时间';
COMMENT ON COLUMN "tool_calls"."ended_at" IS '结束时间';
COMMENT ON COLUMN "tool_calls"."created_at" IS '创建时间';
COMMENT ON COLUMN "tool_calls"."updated_at" IS '最后更新时间';
COMMENT ON COLUMN "tool_capabilities"."id" IS '主键';
COMMENT ON COLUMN "tool_capabilities"."workspace_id" IS '所属工作空间';
COMMENT ON COLUMN "tool_capabilities"."key" IS '稳定键';
COMMENT ON COLUMN "tool_capabilities"."version_number" IS '版本号';
COMMENT ON COLUMN "tool_capabilities"."name" IS '名称';
COMMENT ON COLUMN "tool_capabilities"."description" IS '说明';
COMMENT ON COLUMN "tool_capabilities"."status" IS '状态';
COMMENT ON COLUMN "tool_capabilities"."transport" IS '传输方式：native / mcp';
COMMENT ON COLUMN "tool_capabilities"."adapter_key" IS '适配器键';
COMMENT ON COLUMN "tool_capabilities"."input_schema" IS '输入 schema';
COMMENT ON COLUMN "tool_capabilities"."output_schema" IS '输出 schema';
COMMENT ON COLUMN "tool_capabilities"."schema_digest" IS 'schema 摘要';
COMMENT ON COLUMN "tool_capabilities"."effect_class" IS '工具副作用类别';
COMMENT ON COLUMN "tool_capabilities"."risk" IS '风险等级';
COMMENT ON COLUMN "tool_capabilities"."credential_policy_ref" IS '凭据策略引用';
COMMENT ON COLUMN "tool_capabilities"."network_policy" IS '网络策略';
COMMENT ON COLUMN "tool_capabilities"."approval_policy" IS '审批策略';
COMMENT ON COLUMN "tool_capabilities"."max_duration_ms" IS '最长执行毫秒';
COMMENT ON COLUMN "tool_capabilities"."max_response_bytes" IS '最大响应字节';
COMMENT ON COLUMN "tool_capabilities"."created_by_actor_id" IS '创建人 Actor';
COMMENT ON COLUMN "tool_capabilities"."activated_at" IS '启用时间';
COMMENT ON COLUMN "tool_capabilities"."created_at" IS '创建时间';
COMMENT ON COLUMN "tool_capabilities"."updated_at" IS '最后更新时间';
COMMENT ON COLUMN "tool_effects"."id" IS '主键';
COMMENT ON COLUMN "tool_effects"."workspace_id" IS '所属工作空间';
COMMENT ON COLUMN "tool_effects"."tool_call_id" IS '关联工具调用';
COMMENT ON COLUMN "tool_effects"."status" IS '状态';
COMMENT ON COLUMN "tool_effects"."external_idempotency_key" IS '外部幂等键';
COMMENT ON COLUMN "tool_effects"."request_digest" IS '请求摘要';
COMMENT ON COLUMN "tool_effects"."result_digest" IS '结果摘要';
COMMENT ON COLUMN "tool_effects"."dispatched_at" IS '已派发时间';
COMMENT ON COLUMN "tool_effects"."confirmed_at" IS '确认时间';
COMMENT ON COLUMN "tool_effects"."created_at" IS '创建时间';
COMMENT ON COLUMN "tool_effects"."updated_at" IS '最后更新时间';
COMMENT ON COLUMN "usage_ledger_entries"."id" IS '主键';
COMMENT ON COLUMN "usage_ledger_entries"."workspace_id" IS '所属工作空间';
COMMENT ON COLUMN "usage_ledger_entries"."project_id" IS '所属项目';
COMMENT ON COLUMN "usage_ledger_entries"."run_id" IS '关联 Agent 运行';
COMMENT ON COLUMN "usage_ledger_entries"."actor_id" IS '关联 Actor';
COMMENT ON COLUMN "usage_ledger_entries"."agent_version_id" IS '使用的 Agent 版本';
COMMENT ON COLUMN "usage_ledger_entries"."tool_call_id" IS '关联工具调用';
COMMENT ON COLUMN "usage_ledger_entries"."reservation_entry_id" IS '对应预留分录';
COMMENT ON COLUMN "usage_ledger_entries"."entry_type" IS '账本分录类型';
COMMENT ON COLUMN "usage_ledger_entries"."direction" IS '记账方向：debit / credit';
COMMENT ON COLUMN "usage_ledger_entries"."unit" IS '计量单位';
COMMENT ON COLUMN "usage_ledger_entries"."quantity" IS '数量';
COMMENT ON COLUMN "usage_ledger_entries"."monetary_amount_minor" IS '金额最小货币单位';
COMMENT ON COLUMN "usage_ledger_entries"."currency" IS '货币代码';
COMMENT ON COLUMN "usage_ledger_entries"."provider" IS '供应商';
COMMENT ON COLUMN "usage_ledger_entries"."model" IS '模型名';
COMMENT ON COLUMN "usage_ledger_entries"."idempotency_key" IS '幂等键';
COMMENT ON COLUMN "usage_ledger_entries"."occurred_at" IS '发生时间';
COMMENT ON COLUMN "workspace_invitations"."id" IS '主键';
COMMENT ON COLUMN "workspace_invitations"."token_digest" IS '邀请令牌 SHA-256 摘要';
COMMENT ON COLUMN "workspace_invitations"."invited_by_actor_id" IS '邀请人 Actor';
COMMENT ON COLUMN "workspace_invitations"."expires_at" IS '过期时间';
COMMENT ON COLUMN "workspace_invitations"."accepted_by_user_id" IS '接受邀请的用户';
COMMENT ON COLUMN "workspace_invitations"."accepted_at" IS '接受时间';
COMMENT ON COLUMN "workspace_invitations"."revoked_at" IS '撤销时间';
COMMENT ON COLUMN "workspace_invitations"."created_at" IS '创建时间';
COMMENT ON COLUMN "workspace_invitations"."updated_at" IS '最后更新时间';
COMMENT ON COLUMN "workspace_memberships"."invited_by_actor_id" IS '邀请人 Actor';
COMMENT ON COLUMN "workspace_memberships"."joined_at" IS '加入时间';
COMMENT ON COLUMN "workspace_memberships"."suspended_at" IS '暂停时间';
COMMENT ON COLUMN "workspace_memberships"."left_at" IS '离开时间';
COMMENT ON COLUMN "workspace_memberships"."created_at" IS '创建时间';
COMMENT ON COLUMN "workspace_memberships"."updated_at" IS '最后更新时间';
COMMENT ON COLUMN "workspaces"."created_at" IS '创建时间';
COMMENT ON COLUMN "workspaces"."updated_at" IS '最后更新时间';
COMMENT ON COLUMN "yjs_snapshots"."id" IS '主键';
COMMENT ON COLUMN "yjs_snapshots"."workspace_id" IS '所属工作空间';
COMMENT ON COLUMN "yjs_snapshots"."document_id" IS '所属文档';
COMMENT ON COLUMN "yjs_snapshots"."snapshot_sequence" IS '快照序号';
COMMENT ON COLUMN "yjs_snapshots"."last_update_sequence" IS '快照覆盖到的最后更新序号';
COMMENT ON COLUMN "yjs_snapshots"."kind" IS '类型';
COMMENT ON COLUMN "yjs_snapshots"."state" IS '二进制状态';
COMMENT ON COLUMN "yjs_snapshots"."state_vector" IS 'Yjs 状态向量';
COMMENT ON COLUMN "yjs_snapshots"."state_digest" IS '状态摘要';
COMMENT ON COLUMN "yjs_snapshots"."document_schema_version" IS '文档 schema 版本';
COMMENT ON COLUMN "yjs_snapshots"."created_by_actor_id" IS '创建人 Actor';
COMMENT ON COLUMN "yjs_snapshots"."run_id" IS '关联 Agent 运行';
COMMENT ON COLUMN "yjs_snapshots"."created_at" IS '创建时间';
COMMENT ON COLUMN "yjs_updates"."id" IS '主键';
COMMENT ON COLUMN "yjs_updates"."workspace_id" IS '所属工作空间';
COMMENT ON COLUMN "yjs_updates"."sequence" IS '序号';
COMMENT ON COLUMN "yjs_updates"."update_digest" IS '增量摘要';
COMMENT ON COLUMN "yjs_updates"."actor_id" IS '关联 Actor';
COMMENT ON COLUMN "yjs_updates"."origin" IS '更新来源';
COMMENT ON COLUMN "yjs_updates"."client_mutation_id" IS '客户端幂等键';
COMMENT ON COLUMN "yjs_updates"."run_id" IS '关联 Agent 运行';
COMMENT ON COLUMN "yjs_updates"."transaction_origin" IS '事务来源';
COMMENT ON COLUMN "yjs_updates"."created_at" IS '创建时间';
