import { getTableName } from "drizzle-orm";
import { describe, expect, it } from "vitest";

import {
  actors,
  accessRoles,
  actorRoleAssignments,
  agentProfiles,
  agentRuns,
  agentVersions,
  approvals,
  auditEvents,
  authAccounts,
  authSessions,
  authVerifications,
  capabilities,
  contextManifests,
  documentProposals,
  documentVersions,
  documents,
  humanActors,
  mentions,
  messageRevisions,
  messages,
  outboxEvents,
  projects,
  proposalOperations,
  roleCapabilityGrants,
  resourceGrants,
  rooms,
  runEvents,
  runSteps,
  toolCalls,
  usageLedgerEntries,
  users,
  workspaceMemberships,
  workspaceInvitations,
  workspaces,
  yjsSnapshots,
  yjsUpdates,
} from "./index";

describe("database schema exports", () => {
  it("exports every required domain aggregate with a unique SQL table name", () => {
    const requiredTables = [
      users,
      workspaces,
      actors,
      accessRoles,
      actorRoleAssignments,
      humanActors,
      workspaceMemberships,
      capabilities,
      roleCapabilityGrants,
      resourceGrants,
      projects,
      rooms,
      messages,
      messageRevisions,
      mentions,
      agentProfiles,
      agentVersions,
      agentRuns,
      runEvents,
      runSteps,
      toolCalls,
      contextManifests,
      documents,
      yjsUpdates,
      yjsSnapshots,
      documentVersions,
      documentProposals,
      proposalOperations,
      approvals,
      auditEvents,
      usageLedgerEntries,
      outboxEvents,
      authAccounts,
      authSessions,
      authVerifications,
      workspaceInvitations,
    ];
    const names = requiredTables.map((table) => getTableName(table));

    expect(names).toHaveLength(36);
    expect(new Set(names).size).toBe(names.length);
  });
});
